## Makefile for Windows NT: Numeric include files installation 
## $Id: Makefile.nt,v 1.1 2001-04-10 11:18:51 yad Exp $


DIRS=GradSoft

install:
	@for %i in ( $(DIRS) ) do \
		@cd %i & $(MAKE) /F Makefile.nt install

uninstall:
	@for %i in ( $(DIRS) ) do \
		@cd %i & $(MAKE) /F Makefile.nt uninstall
