# Makefile for ProgOptions project for WinNT: source code compilation
# $Id: Makefile.nt,v 1.10 2001-12-11 20:56:36 kav Exp $

############################################
!ifndef PROJECT_ROOT       #               #
PROJECT_ROOT=$(MAKEDIR)\.. # debug entries #
!endif                     #               #
############################################

include ..\..\config\Win32\environment.nt.mak
include ..\config\common_settings.nt.mak

OBJS = ProgOptions.obj StringPtrWithLen.obj
LIBS = $(SLIB)

default: build

install: makedir build ; $(INSTALL) $(SLIB) $(INSTALL_LIB_DIR)

makedir: ; @if not exist $(INSTALL_LIB_DIR) mkdir $(INSTALL_LIB_DIR)

build: $(LIBS) 

$(SLIB): $(OBJS) ; $(AR) $(ARFLAGS) $(OBJS)

uninstall: ;

   @for %i in ( $(LIBS) ) do @if exist $(INSTALL_LIB_DIR)\%i $(REMOVE) $(INSTALL_LIB_DIR)\%i

clean: ; @for %i in ( $(LIBS) $(OBJS) ) do @if exist %i $(REMOVE) %i

.cpp.obj:: ; $(CPP) $< $(CPPFLAGS) 
