## Makefile for Windows NT: Threading usage sample compilation
## $Id: makefile.nt,v 1.6 2003-10-10 15:34:37 rssh Exp $

###############################################
!ifndef PROJECT_ROOT          #               #
PROJECT_ROOT=$(MAKEDIR)\..\.. # debug entries #
!endif                        #               #
###############################################

include ..\..\config\common_settings.nt.mak

build: Philosophs.exe

Philosophs.exe: $(THREADING_LIBS) Philosophs.obj ; $(LD) Philosophs.obj $(LDFLAGS) $(THREADING_LIBS) 

clean: ; @for %i in ( Philosophs.exe Philosophs.obj ) do @if exist %i $(REMOVE) %i
