## Makefile for Windows NT: SMTPMailer include files installation 
## $Id: Makefile.nt,v 1.2 2001-04-27 09:55:38 srkr Exp $

include ..\..\..\..\config\env_inc.nt.mak
include ..\..\config\env_inc.nt.mak

install: install-headers

DIR=GradSoft
GradSoft_INSTALL=\
	SMTPMailer.h

install-headers::
	@if not exist $(INSTALL_INC_DIR) mkdir $(INSTALL_INC_DIR)
	@if not exist $(INSTALL_INC_DIR)\$(DIR) mkdir $(INSTALL_INC_DIR)\$(DIR)
	@for %i in ( $(GradSoft_INSTALL) ) do \
		$(INSTALL_DATA) %i $(INSTALL_INC_DIR)\$(DIR)
uninstall:
	@for %i in ( $(GradSoft_INSTALL) ) do \
	@if exist $(INSTALL_INC_DIR)\$(DIR)\%i $(RM) $(INSTALL_INC_DIR)\$(DIR)\%i
