## Makefile for Windows NT: Threading include files installation 
## (C) GradSoft 2000, 2001
## $Id: Makefile.nt,v 1.11 2008-01-08 17:14:07 rssh Exp $

include ..\..\..\config\Win32\environment.nt.mak
include ..\..\config\common_settings.nt.mak

TARGET_DIR=$(INSTALL_INC_DIR)\GradSoft

PURVEYANCE=\
 counted_mt_ptr.h \
 Mutex.h \
 Runnable.h \
 RWLock.h \
 Thread.h \
 ThreadContext.h \
 ThreadEvent.h \
 Threading.h \
 ThreadingConfigNT.h \
 ThreadingExceptions.h \
 ThreadingPostConfig.h \
 ThreadingUtils.h \
 ThreadsafeContainers.h \
 ThreadService.h

install: makedir
   @for %i in ( $(PURVEYANCE) ) do @$(INSTALL) %i $(TARGET_DIR)

makedir:
   @if not exist $(TARGET_DIR) mkdir $(TARGET_DIR)

uninstall:
   @for %i in ( $(PURVEYANCE) ) do @if exist $(TARGET_DIR)\%i $(REMOVE) $(TARGET_DIR)\%i

