## Main Makefile for SMTPmailer project  for WinNT
## $Id: Makefile.nt,v 1.1 2001-02-09 15:02:33 yad Exp $

include ..\..\config\env_inc.nt.mak
include .\config\env_inc.nt.mak


SUBDIRS=$(PROJECT_ROOT)\src $(PROJECT_ROOT)\demo

INSTALL_DIRS=$(PROJECT_ROOT)\src $(PROJECT_ROOT)\include $(PROJECT_ROOT)\..\Socket\include



default: build


build::
	@for %i in ( $(SUBDIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt build

install:: 
	@for %i in ( $(INSTALL_DIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt install

uninstall:: 
	@for %i in ( $(INSTALL_DIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt uninstall

clean:: 
	@for %i in ($(SUBDIRS)) do \
		@cd %i && $(MAKE) /F Makefile.nt clean

