## Makefile for Windows NT: Threading usage sample compilation
## $Id: makefile.nt,v 1.5 2003-10-10 15:34:37 rssh Exp $

###############################################
!ifndef PROJECT_ROOT          #               #
PROJECT_ROOT=$(MAKEDIR)\..\.. # debug entries #
!endif                        #               #
###############################################

include ..\..\config\common_settings.nt.mak

build: MaxThreads.exe

MaxThreads.exe: $(THREADING_LIBS) MaxThreads.obj ; $(LD) MaxThreads.obj $(LDFLAGS)  $(THREADING_LIBS)

clean: ; @for %i in ( MaxThreads.exe MaxThreads.obj ) do @if exist %i $(REMOVE) %i

