## Makefile for Windows NT
## part of GradSoft C++ ToolBox
## $Id: makefile.nt,v 1.3 2001-10-10 12:42:52 yad Exp $

include ..\..\config\env_inc.nt.mak
include ..\config\env_inc.nt.mak

DEMO_DIR=$(PROJECT_ROOT)\demo

default: build

build: $(DEMO_DIR)\demo.exe

$(DEMO_DIR)\demo.exe: $(DEMO_DIR)\demo.obj
	$(LINKEXE) $(LIB) $(DEMO_DIR)\demo.obj 
	
$(DEMO_DIR)\demo.obj: $(DEMO_DIR)\demo.cpp
	$(CXXCOMPILE) $(DEMO_INCLUDE) $(DEMO_DIR)\demo.cpp

clean:
	$(RM) $(DEMO_DIR)\*.obj $(DEMO_DIR)\*.exe
