## Project Threading; Makefile for Windows; compilation of test application
## $Id: Makefile.nt,v 1.4 2003-10-10 15:34:35 rssh Exp $

###############################################
!ifndef PROJECT_ROOT          #               #
PROJECT_ROOT=$(MAKEDIR)\..\.. # debug entries #
!endif                        #               #
###############################################

include ..\..\config\common_settings.nt.mak

build: DeleteThis.exe

DeleteThis.exe: $(THREADING_LIBS) DeleteThis.obj ; $(LD) DeleteThis.obj $(LDFLAGS)  $(THREADING_LIBS)

clean: ; @for %i in ( DeleteThis.exe DeleteThis.obj ) do @if exist %i $(REMOVE) %i


