## Makefile for Windows NT: Crypt include files installation 
## $Id: Makefile.nt,v 1.1 2001-04-10 11:34:28 yad Exp $

include ..\..\..\config\env_inc.nt.mak
include ..\..\config\env_inc.nt.mak

install: install-headers

DIR=GradSoft
GradSoft_INSTALL=\
	CryptHelper \
	CryptHelper.h 

install-headers::
	@if not exist $(INSTALL_INC_DIR) mkdir $(INSTALL_INC_DIR)
	@if not exist $(INSTALL_INC_DIR)\$(DIR) mkdir $(INSTALL_INC_DIR)\$(DIR)
	@for %i in ( $(GradSoft_INSTALL) ) do \
		$(INSTALL_DATA) %i $(INSTALL_INC_DIR)\$(DIR)
uninstall:
	@for %i in ( $(GradSoft_INSTALL) ) do \
	@if exist $(INSTALL_INC_DIR)\$(DIR)\%i $(RM) $(INSTALL_INC_DIR)\$(DIR)\%i
