# (C) Grad-Soft Ltd, Kiev, Ukraine 2001
# http://www.gradsoft.com.ua/eng/
# $Id: Makefile.nt,v 1.2 2001-12-27 16:02:15 kav Exp $
#


SUBDIRS=$(MAKEDIR)\Hello
        

build: 
	@for %i in ( $(SUBDIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt build

install:
uninstall:

clean:
	@for %i in ( $(SUBDIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt clean

