## Main Makefile for ptrs project  for WinNT
## $Id: Makefile.nt,v 1.1 2002-03-16 19:03:57 kav Exp $

SUBDIRS_COMPILE=demo
SUBDIRS_INSTALL=include

default: build

build:
	@for %i in ( $(SUBDIRS_COMPILE) ) do \
	@cd $(MAKEDIR)\%i && $(MAKE) /F Makefile.nt PROJECT_ROOT="$(MAKEDIR)" build

install:
	@for %i in ( $(SUBDIRS_INSTALL) ) do \
	@cd $(MAKEDIR)\%i && $(MAKE) /F Makefile.nt install

uninstall: 
	@for %i in ( $(SUBDIRS_INSTALL) ) do \
	@cd $(MAKEDIR)\%i && $(MAKE) /F Makefile.nt uninstall

clean:
	@for %i in ($(SUBDIRS_COMPILE)) do \
	@cd $(MAKEDIR)\%i && $(MAKE) /F Makefile.nt clean

