## Main Makefile for Signaling project  for WinNT
## $Id: makefile.nt,v 1.2 2001-10-01 15:18:28 yad Exp $

include ..\config\env_inc.nt.mak
include .\config\env_inc.nt.mak


SUBDIRS=$(PROJECT_ROOT)\src $(PROJECT_ROOT)\demo

INSTALL_DIRS=$(PROJECT_ROOT)\include



default: build


build::
	@for %i in ( $(SUBDIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt build

install:: 
	@for %i in ( $(INSTALL_DIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt install

uninstall:: 
	@for %i in ( $(INSTALL_DIRS) ) do \
		@cd %i && $(MAKE) /F Makefile.nt uninstall

clean:: 
	@for %i in ($(SUBDIRS)) do \
		@cd %i && $(MAKE) /F Makefile.nt clean

