## Makefile for Windows NT: Signaling include files installation 
## $Id: Makefile.nt,v 1.1 2001-08-20 13:06:28 yad Exp $


DIRS=GradSoft

install:
	@for %i in ( $(DIRS) ) do \
		@cd %i & $(MAKE) /F Makefile.nt install

uninstall:
	@for %i in ( $(DIRS) ) do \
		@cd %i & $(MAKE) /F Makefile.nt uninstall
