## Makefile for Windows NT: ProgOptions include files installation 
## $Id: Makefile.nt,v 1.7 2001-12-11 20:56:32 kav Exp $


DIRECTORIES=$(MAKEDIR)\GradSoft

install:
  @for %i in ( $(DIRECTORIES) ) do @cd %i && $(MAKE) /F Makefile.nt install

uninstall:
  @for %i in ( $(DIRECTORIES) ) do @cd %i && $(MAKE) /F Makefile.nt uninstall
