# Generated automatically from Makefile.in by configure.
PROJECT_ROOT=.
include $(PROJECT_ROOT)/../../config/entry.mak

PthreadSysTest: PthreadSysTest.o
	$(CXX) $(CXXFLAGS) -o PthreadSysTest PthreadSysTest.o 
	
PthreadSysTest.o: PthreadSysTest.cpp
	$(CXX) $(CXXFLAGS) -c PthreadSysTest.cpp

default: build

build: PthreadSysTest 

install:
uninstall:

clean:
	-rm *.o PthreadSysTest 
	-rm -rf Templates.DB
