## Makefile for Windows NT: Threading usage sample compilation
## $Id: makefile.nt,v 1.5 2003-10-10 15:34:39 rssh Exp $

###############################################
!ifndef PROJECT_ROOT          #               #
PROJECT_ROOT=$(MAKEDIR)\..\.. # debug entries #
!endif                        #               #
###############################################

include ..\..\config\common_settings.nt.mak

build: ThreadServiceDemo.exe

ThreadServiceDemo.exe: $(THREADING_LIBS) ThreadServiceDemo.obj ;

  $(LD) ThreadServiceDemo.obj $(LDFLAGS)  $(THREADING_LIBS)

clean: ; @for %i in ( ThreadServiceDemo.exe ThreadServiceDemo.obj ) do @if exist %i $(REMOVE) %i
