## Makefile for Windows NT
## $Id: Makefile.nt,v 1.1 2002-07-31 07:54:54 rin Exp $

DIRECTORIES=$(MAKEDIR)\GradSoft

install:
  @for %i in ( $(DIRECTORIES) ) do @cd %i && $(MAKE) /F Makefile.nt install

uninstall:
  @for %i in ( $(DIRECTORIES) ) do @cd %i && $(MAKE) /F Makefile.nt uninstall

build:

clean:
