## Makefile for Windows NT
## part of GradSoft C++ ToolBox
## $Id: Makefile.nt,v 1.1 2002-03-16 19:03:58 kav Exp $

############################################
!ifndef PROJECT_ROOT       #               #
PROJECT_ROOT=$(MAKEDIR)\.. # debug entries #
!endif                     #               #
############################################

DIRS = auto_array_ptr owned_ptr safe_ptr

build: ;
  @for %i in ( $(DIRS) ) do \
  @cd $(MAKEDIR)\%i && $(MAKE) /F Makefile.nt PROJECT_ROOT="$(PROJECT_ROOT)" build

clean: ;
  @for %i in ( $(DIRS) ) do \
  @cd $(MAKEDIR)\%i && $(MAKE) /F Makefile.nt clean
